# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: functions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'functions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66unctions.proto\")\n\x12QuestionToQueryReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\":\n\x14QuestionToQueryReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"$\n\rRetrieval1Req\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"5\n\x0fRetrieval1Reply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"$\n\rRetrieval2Req\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"5\n\x0fRetrieval2Reply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"0\n\x19\x43ontextQuestionToQueryReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"A\n\x1b\x43ontextQuestionToQueryReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"1\n\x1a\x43ontextQuestionToAnswerReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"B\n\x1c\x43ontextQuestionToAnswerReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\" \n\tRerankReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"1\n\x0bRerankReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"&\n\x0fQaEvaluationReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"7\n\x11QaEvaluationReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xbe\x03\n\x0f\x46unctionService\x12?\n\x11question_to_query\x12\x13.QuestionToQueryReq\x1a\x15.QuestionToQueryReply\x12U\n\x19\x63ontext_question_to_query\x12\x1a.ContextQuestionToQueryReq\x1a\x1c.ContextQuestionToQueryReply\x12X\n\x1a\x63ontext_question_to_answer\x12\x1b.ContextQuestionToAnswerReq\x1a\x1d.ContextQuestionToAnswerReply\x12\"\n\x06rerank\x12\n.RerankReq\x1a\x0c.RerankReply\x12.\n\nretrieval1\x12\x0e.Retrieval1Req\x1a\x10.Retrieval1Reply\x12.\n\nretrieval2\x12\x0e.Retrieval2Req\x1a\x10.Retrieval2Reply\x12\x35\n\rqa_evaluation\x12\x10.QaEvaluationReq\x1a\x12.QaEvaluationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'functions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTIONTOQUERYREQ']._serialized_start=19
  _globals['_QUESTIONTOQUERYREQ']._serialized_end=60
  _globals['_QUESTIONTOQUERYREPLY']._serialized_start=62
  _globals['_QUESTIONTOQUERYREPLY']._serialized_end=120
  _globals['_RETRIEVAL1REQ']._serialized_start=122
  _globals['_RETRIEVAL1REQ']._serialized_end=158
  _globals['_RETRIEVAL1REPLY']._serialized_start=160
  _globals['_RETRIEVAL1REPLY']._serialized_end=213
  _globals['_RETRIEVAL2REQ']._serialized_start=215
  _globals['_RETRIEVAL2REQ']._serialized_end=251
  _globals['_RETRIEVAL2REPLY']._serialized_start=253
  _globals['_RETRIEVAL2REPLY']._serialized_end=306
  _globals['_CONTEXTQUESTIONTOQUERYREQ']._serialized_start=308
  _globals['_CONTEXTQUESTIONTOQUERYREQ']._serialized_end=356
  _globals['_CONTEXTQUESTIONTOQUERYREPLY']._serialized_start=358
  _globals['_CONTEXTQUESTIONTOQUERYREPLY']._serialized_end=423
  _globals['_CONTEXTQUESTIONTOANSWERREQ']._serialized_start=425
  _globals['_CONTEXTQUESTIONTOANSWERREQ']._serialized_end=474
  _globals['_CONTEXTQUESTIONTOANSWERREPLY']._serialized_start=476
  _globals['_CONTEXTQUESTIONTOANSWERREPLY']._serialized_end=542
  _globals['_RERANKREQ']._serialized_start=544
  _globals['_RERANKREQ']._serialized_end=576
  _globals['_RERANKREPLY']._serialized_start=578
  _globals['_RERANKREPLY']._serialized_end=627
  _globals['_QAEVALUATIONREQ']._serialized_start=629
  _globals['_QAEVALUATIONREQ']._serialized_end=667
  _globals['_QAEVALUATIONREPLY']._serialized_start=669
  _globals['_QAEVALUATIONREPLY']._serialized_end=724
  _globals['_FUNCTIONSERVICE']._serialized_start=727
  _globals['_FUNCTIONSERVICE']._serialized_end=1173
# @@protoc_insertion_point(module_scope)
