# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import functions_pb2 as functions__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in functions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FunctionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.question_to_query = channel.unary_unary(
                '/FunctionService/question_to_query',
                request_serializer=functions__pb2.QuestionToQueryReq.SerializeToString,
                response_deserializer=functions__pb2.QuestionToQueryReply.FromString,
                _registered_method=True)
        self.context_question_to_query = channel.unary_unary(
                '/FunctionService/context_question_to_query',
                request_serializer=functions__pb2.ContextQuestionToQueryReq.SerializeToString,
                response_deserializer=functions__pb2.ContextQuestionToQueryReply.FromString,
                _registered_method=True)
        self.context_question_to_answer = channel.unary_unary(
                '/FunctionService/context_question_to_answer',
                request_serializer=functions__pb2.ContextQuestionToAnswerReq.SerializeToString,
                response_deserializer=functions__pb2.ContextQuestionToAnswerReply.FromString,
                _registered_method=True)
        self.rerank = channel.unary_unary(
                '/FunctionService/rerank',
                request_serializer=functions__pb2.RerankReq.SerializeToString,
                response_deserializer=functions__pb2.RerankReply.FromString,
                _registered_method=True)
        self.retrieval1 = channel.unary_unary(
                '/FunctionService/retrieval1',
                request_serializer=functions__pb2.Retrieval1Req.SerializeToString,
                response_deserializer=functions__pb2.Retrieval1Reply.FromString,
                _registered_method=True)
        self.retrieval2 = channel.unary_unary(
                '/FunctionService/retrieval2',
                request_serializer=functions__pb2.Retrieval2Req.SerializeToString,
                response_deserializer=functions__pb2.Retrieval2Reply.FromString,
                _registered_method=True)
        self.qa_evaluation = channel.unary_unary(
                '/FunctionService/qa_evaluation',
                request_serializer=functions__pb2.QaEvaluationReq.SerializeToString,
                response_deserializer=functions__pb2.QaEvaluationReply.FromString,
                _registered_method=True)


class FunctionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def question_to_query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def context_question_to_query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def context_question_to_answer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rerank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieval1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieval2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def qa_evaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FunctionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'question_to_query': grpc.unary_unary_rpc_method_handler(
                    servicer.question_to_query,
                    request_deserializer=functions__pb2.QuestionToQueryReq.FromString,
                    response_serializer=functions__pb2.QuestionToQueryReply.SerializeToString,
            ),
            'context_question_to_query': grpc.unary_unary_rpc_method_handler(
                    servicer.context_question_to_query,
                    request_deserializer=functions__pb2.ContextQuestionToQueryReq.FromString,
                    response_serializer=functions__pb2.ContextQuestionToQueryReply.SerializeToString,
            ),
            'context_question_to_answer': grpc.unary_unary_rpc_method_handler(
                    servicer.context_question_to_answer,
                    request_deserializer=functions__pb2.ContextQuestionToAnswerReq.FromString,
                    response_serializer=functions__pb2.ContextQuestionToAnswerReply.SerializeToString,
            ),
            'rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.rerank,
                    request_deserializer=functions__pb2.RerankReq.FromString,
                    response_serializer=functions__pb2.RerankReply.SerializeToString,
            ),
            'retrieval1': grpc.unary_unary_rpc_method_handler(
                    servicer.retrieval1,
                    request_deserializer=functions__pb2.Retrieval1Req.FromString,
                    response_serializer=functions__pb2.Retrieval1Reply.SerializeToString,
            ),
            'retrieval2': grpc.unary_unary_rpc_method_handler(
                    servicer.retrieval2,
                    request_deserializer=functions__pb2.Retrieval2Req.FromString,
                    response_serializer=functions__pb2.Retrieval2Reply.SerializeToString,
            ),
            'qa_evaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.qa_evaluation,
                    request_deserializer=functions__pb2.QaEvaluationReq.FromString,
                    response_serializer=functions__pb2.QaEvaluationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FunctionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FunctionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FunctionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def question_to_query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/question_to_query',
            functions__pb2.QuestionToQueryReq.SerializeToString,
            functions__pb2.QuestionToQueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def context_question_to_query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/context_question_to_query',
            functions__pb2.ContextQuestionToQueryReq.SerializeToString,
            functions__pb2.ContextQuestionToQueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def context_question_to_answer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/context_question_to_answer',
            functions__pb2.ContextQuestionToAnswerReq.SerializeToString,
            functions__pb2.ContextQuestionToAnswerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/rerank',
            functions__pb2.RerankReq.SerializeToString,
            functions__pb2.RerankReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def retrieval1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/retrieval1',
            functions__pb2.Retrieval1Req.SerializeToString,
            functions__pb2.Retrieval1Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def retrieval2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/retrieval2',
            functions__pb2.Retrieval2Req.SerializeToString,
            functions__pb2.Retrieval2Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def qa_evaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/qa_evaluation',
            functions__pb2.QaEvaluationReq.SerializeToString,
            functions__pb2.QaEvaluationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
