# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actor_learner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'actor_learner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x63tor_learner.proto\x12\ractor_learner\"\xc5\x01\n\nExperience\x12\x18\n\x10state_graph_part\x18\x01 \x01(\t\x12\x15\n\rtask_question\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0e\n\x06reward\x18\x04 \x01(\x02\x12\x1d\n\x15next_state_graph_part\x18\x05 \x01(\t\x12\x0c\n\x04\x64one\x18\x06 \x01(\x08\x12\x19\n\x11\x61vailable_actions\x18\x07 \x03(\t\x12\x1e\n\x16next_available_actions\x18\x08 \x03(\t\"\xb1\x01\n\x14RegisterActorRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\x05\x12\x43\n\x08metadata\x18\x02 \x03(\x0b\x32\x31.actor_learner.RegisterActorRequest.MetadataEntry\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"9\n\x15RegisterActorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"m\n\x16SendExperiencesRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\x05\x12.\n\x0b\x65xperiences\x18\x02 \x03(\x0b\x32\x19.actor_learner.Experience\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\";\n\x17SendExperiencesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"=\n\x16GetModelWeightsRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\"W\n\x17GetModelWeightsResponse\x12\x12\n\nhas_update\x18\x01 \x01(\x08\x12\x15\n\rmodel_weights\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x32\xb0\x02\n\x0eLearnerService\x12Z\n\rRegisterActor\x12#.actor_learner.RegisterActorRequest\x1a$.actor_learner.RegisterActorResponse\x12`\n\x0fSendExperiences\x12%.actor_learner.SendExperiencesRequest\x1a&.actor_learner.SendExperiencesResponse\x12`\n\x0fGetModelWeights\x12%.actor_learner.GetModelWeightsRequest\x1a&.actor_learner.GetModelWeightsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actor_learner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERACTORREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_REGISTERACTORREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EXPERIENCE']._serialized_start=39
  _globals['_EXPERIENCE']._serialized_end=236
  _globals['_REGISTERACTORREQUEST']._serialized_start=239
  _globals['_REGISTERACTORREQUEST']._serialized_end=416
  _globals['_REGISTERACTORREQUEST_METADATAENTRY']._serialized_start=369
  _globals['_REGISTERACTORREQUEST_METADATAENTRY']._serialized_end=416
  _globals['_REGISTERACTORRESPONSE']._serialized_start=418
  _globals['_REGISTERACTORRESPONSE']._serialized_end=475
  _globals['_SENDEXPERIENCESREQUEST']._serialized_start=477
  _globals['_SENDEXPERIENCESREQUEST']._serialized_end=586
  _globals['_SENDEXPERIENCESRESPONSE']._serialized_start=588
  _globals['_SENDEXPERIENCESRESPONSE']._serialized_end=647
  _globals['_GETMODELWEIGHTSREQUEST']._serialized_start=649
  _globals['_GETMODELWEIGHTSREQUEST']._serialized_end=710
  _globals['_GETMODELWEIGHTSRESPONSE']._serialized_start=712
  _globals['_GETMODELWEIGHTSRESPONSE']._serialized_end=799
  _globals['_LEARNERSERVICE']._serialized_start=802
  _globals['_LEARNERSERVICE']._serialized_end=1106
# @@protoc_insertion_point(module_scope)
