# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import actor_learner_pb2 as actor__learner__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION,
                                                    GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},' +
        f' but the generated code in actor_learner_pb2_grpc.py depends on' +
        f' grpcio>={GRPC_GENERATED_VERSION}.' +
        f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        +
        f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LearnerServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterActor = channel.unary_unary(
            '/actor_learner.LearnerService/RegisterActor',
            request_serializer=actor__learner__pb2.RegisterActorRequest.
            SerializeToString,
            response_deserializer=actor__learner__pb2.RegisterActorResponse.
            FromString,
            _registered_method=True)
        self.SendExperiences = channel.unary_unary(
            '/actor_learner.LearnerService/SendExperiences',
            request_serializer=actor__learner__pb2.SendExperiencesRequest.
            SerializeToString,
            response_deserializer=actor__learner__pb2.SendExperiencesResponse.
            FromString,
            _registered_method=True)
        self.GetModelWeights = channel.unary_unary(
            '/actor_learner.LearnerService/GetModelWeights',
            request_serializer=actor__learner__pb2.GetModelWeightsRequest.
            SerializeToString,
            response_deserializer=actor__learner__pb2.GetModelWeightsResponse.
            FromString,
            _registered_method=True)


class LearnerServiceServicer(object):
    """Service definition
    """

    def RegisterActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendExperiences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'RegisterActor':
        grpc.unary_unary_rpc_method_handler(
            servicer.RegisterActor,
            request_deserializer=actor__learner__pb2.RegisterActorRequest.
            FromString,
            response_serializer=actor__learner__pb2.RegisterActorResponse.
            SerializeToString,
        ),
        'SendExperiences':
        grpc.unary_unary_rpc_method_handler(
            servicer.SendExperiences,
            request_deserializer=actor__learner__pb2.SendExperiencesRequest.
            FromString,
            response_serializer=actor__learner__pb2.SendExperiencesResponse.
            SerializeToString,
        ),
        'GetModelWeights':
        grpc.unary_unary_rpc_method_handler(
            servicer.GetModelWeights,
            request_deserializer=actor__learner__pb2.GetModelWeightsRequest.
            FromString,
            response_serializer=actor__learner__pb2.GetModelWeightsResponse.
            SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'actor_learner.LearnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler, ))
    server.add_registered_method_handlers('actor_learner.LearnerService',
                                          rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class LearnerService(object):
    """Service definition
    """

    @staticmethod
    def RegisterActor(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actor_learner.LearnerService/RegisterActor',
            actor__learner__pb2.RegisterActorRequest.SerializeToString,
            actor__learner__pb2.RegisterActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendExperiences(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actor_learner.LearnerService/SendExperiences',
            actor__learner__pb2.SendExperiencesRequest.SerializeToString,
            actor__learner__pb2.SendExperiencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelWeights(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actor_learner.LearnerService/GetModelWeights',
            actor__learner__pb2.GetModelWeightsRequest.SerializeToString,
            actor__learner__pb2.GetModelWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
