# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import functions_pb2 as functions__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in functions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FunctionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.candidate_generation = channel.unary_unary(
                '/FunctionService/candidate_generation',
                request_serializer=functions__pb2.CandidateGenerationReq.SerializeToString,
                response_deserializer=functions__pb2.CandidateGenerationReply.FromString,
                _registered_method=True)
        self.column_filtering = channel.unary_unary(
                '/FunctionService/column_filtering',
                request_serializer=functions__pb2.ColumnFilteringReq.SerializeToString,
                response_deserializer=functions__pb2.ColumnFilteringReply.FromString,
                _registered_method=True)
        self.column_selection = channel.unary_unary(
                '/FunctionService/column_selection',
                request_serializer=functions__pb2.ColumnSelectionReq.SerializeToString,
                response_deserializer=functions__pb2.ColumnSelectionReply.FromString,
                _registered_method=True)
        self.context_retrieval = channel.unary_unary(
                '/FunctionService/context_retrieval',
                request_serializer=functions__pb2.ContextRetrievalReq.SerializeToString,
                response_deserializer=functions__pb2.ContextRetrievalReply.FromString,
                _registered_method=True)
        self.entity_retrieval = channel.unary_unary(
                '/FunctionService/entity_retrieval',
                request_serializer=functions__pb2.EntityRetrievalReq.SerializeToString,
                response_deserializer=functions__pb2.EntityRetrievalReply.FromString,
                _registered_method=True)
        self.evaluation = channel.unary_unary(
                '/FunctionService/evaluation',
                request_serializer=functions__pb2.EvaluationReq.SerializeToString,
                response_deserializer=functions__pb2.EvaluationReply.FromString,
                _registered_method=True)
        self.keyword_extraction = channel.unary_unary(
                '/FunctionService/keyword_extraction',
                request_serializer=functions__pb2.KeywordExtractionReq.SerializeToString,
                response_deserializer=functions__pb2.KeywordExtractionReply.FromString,
                _registered_method=True)
        self.revision = channel.unary_unary(
                '/FunctionService/revision',
                request_serializer=functions__pb2.RevisionReq.SerializeToString,
                response_deserializer=functions__pb2.RevisionReply.FromString,
                _registered_method=True)
        self.table_selection = channel.unary_unary(
                '/FunctionService/table_selection',
                request_serializer=functions__pb2.TableSelectionReq.SerializeToString,
                response_deserializer=functions__pb2.TableSelectionReply.FromString,
                _registered_method=True)
        self.preprocess = channel.unary_unary(
                '/FunctionService/preprocess',
                request_serializer=functions__pb2.PreprocessReq.SerializeToString,
                response_deserializer=functions__pb2.PreprocessReply.FromString,
                _registered_method=True)
        self.processor = channel.unary_unary(
                '/FunctionService/processor',
                request_serializer=functions__pb2.ProcessorReq.SerializeToString,
                response_deserializer=functions__pb2.ProcessorReply.FromString,
                _registered_method=True)
        self.composer = channel.unary_unary(
                '/FunctionService/composer',
                request_serializer=functions__pb2.ComposerReq.SerializeToString,
                response_deserializer=functions__pb2.ComposerReply.FromString,
                _registered_method=True)
        self.validator = channel.unary_unary(
                '/FunctionService/validator',
                request_serializer=functions__pb2.ValidatorReq.SerializeToString,
                response_deserializer=functions__pb2.ValidatorReply.FromString,
                _registered_method=True)
        self.nv_evaluation = channel.unary_unary(
                '/FunctionService/nv_evaluation',
                request_serializer=functions__pb2.NvEvaluationReq.SerializeToString,
                response_deserializer=functions__pb2.NvEvaluationReply.FromString,
                _registered_method=True)
        self.question_to_query = channel.unary_unary(
                '/FunctionService/question_to_query',
                request_serializer=functions__pb2.QuestionToQueryReq.SerializeToString,
                response_deserializer=functions__pb2.QuestionToQueryReply.FromString,
                _registered_method=True)
        self.context_question_to_query = channel.unary_unary(
                '/FunctionService/context_question_to_query',
                request_serializer=functions__pb2.ContextQuestionToQueryReq.SerializeToString,
                response_deserializer=functions__pb2.ContextQuestionToQueryReply.FromString,
                _registered_method=True)
        self.context_question_to_answer = channel.unary_unary(
                '/FunctionService/context_question_to_answer',
                request_serializer=functions__pb2.ContextQuestionToAnswerReq.SerializeToString,
                response_deserializer=functions__pb2.ContextQuestionToAnswerReply.FromString,
                _registered_method=True)
        self.rerank = channel.unary_unary(
                '/FunctionService/rerank',
                request_serializer=functions__pb2.RerankReq.SerializeToString,
                response_deserializer=functions__pb2.RerankReply.FromString,
                _registered_method=True)
        self.retrieval1 = channel.unary_unary(
                '/FunctionService/retrieval1',
                request_serializer=functions__pb2.Retrieval1Req.SerializeToString,
                response_deserializer=functions__pb2.Retrieval1Reply.FromString,
                _registered_method=True)
        self.retrieval2 = channel.unary_unary(
                '/FunctionService/retrieval2',
                request_serializer=functions__pb2.Retrieval2Req.SerializeToString,
                response_deserializer=functions__pb2.Retrieval2Reply.FromString,
                _registered_method=True)
        self.qa_evaluation = channel.unary_unary(
                '/FunctionService/qa_evaluation',
                request_serializer=functions__pb2.QaEvaluationReq.SerializeToString,
                response_deserializer=functions__pb2.QaEvaluationReply.FromString,
                _registered_method=True)


class FunctionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def candidate_generation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def column_filtering(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def column_selection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def context_retrieval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def entity_retrieval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def evaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def keyword_extraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def revision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def table_selection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def preprocess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def composer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def validator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nv_evaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def question_to_query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def context_question_to_query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def context_question_to_answer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rerank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieval1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieval2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def qa_evaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FunctionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'candidate_generation': grpc.unary_unary_rpc_method_handler(
                    servicer.candidate_generation,
                    request_deserializer=functions__pb2.CandidateGenerationReq.FromString,
                    response_serializer=functions__pb2.CandidateGenerationReply.SerializeToString,
            ),
            'column_filtering': grpc.unary_unary_rpc_method_handler(
                    servicer.column_filtering,
                    request_deserializer=functions__pb2.ColumnFilteringReq.FromString,
                    response_serializer=functions__pb2.ColumnFilteringReply.SerializeToString,
            ),
            'column_selection': grpc.unary_unary_rpc_method_handler(
                    servicer.column_selection,
                    request_deserializer=functions__pb2.ColumnSelectionReq.FromString,
                    response_serializer=functions__pb2.ColumnSelectionReply.SerializeToString,
            ),
            'context_retrieval': grpc.unary_unary_rpc_method_handler(
                    servicer.context_retrieval,
                    request_deserializer=functions__pb2.ContextRetrievalReq.FromString,
                    response_serializer=functions__pb2.ContextRetrievalReply.SerializeToString,
            ),
            'entity_retrieval': grpc.unary_unary_rpc_method_handler(
                    servicer.entity_retrieval,
                    request_deserializer=functions__pb2.EntityRetrievalReq.FromString,
                    response_serializer=functions__pb2.EntityRetrievalReply.SerializeToString,
            ),
            'evaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.evaluation,
                    request_deserializer=functions__pb2.EvaluationReq.FromString,
                    response_serializer=functions__pb2.EvaluationReply.SerializeToString,
            ),
            'keyword_extraction': grpc.unary_unary_rpc_method_handler(
                    servicer.keyword_extraction,
                    request_deserializer=functions__pb2.KeywordExtractionReq.FromString,
                    response_serializer=functions__pb2.KeywordExtractionReply.SerializeToString,
            ),
            'revision': grpc.unary_unary_rpc_method_handler(
                    servicer.revision,
                    request_deserializer=functions__pb2.RevisionReq.FromString,
                    response_serializer=functions__pb2.RevisionReply.SerializeToString,
            ),
            'table_selection': grpc.unary_unary_rpc_method_handler(
                    servicer.table_selection,
                    request_deserializer=functions__pb2.TableSelectionReq.FromString,
                    response_serializer=functions__pb2.TableSelectionReply.SerializeToString,
            ),
            'preprocess': grpc.unary_unary_rpc_method_handler(
                    servicer.preprocess,
                    request_deserializer=functions__pb2.PreprocessReq.FromString,
                    response_serializer=functions__pb2.PreprocessReply.SerializeToString,
            ),
            'processor': grpc.unary_unary_rpc_method_handler(
                    servicer.processor,
                    request_deserializer=functions__pb2.ProcessorReq.FromString,
                    response_serializer=functions__pb2.ProcessorReply.SerializeToString,
            ),
            'composer': grpc.unary_unary_rpc_method_handler(
                    servicer.composer,
                    request_deserializer=functions__pb2.ComposerReq.FromString,
                    response_serializer=functions__pb2.ComposerReply.SerializeToString,
            ),
            'validator': grpc.unary_unary_rpc_method_handler(
                    servicer.validator,
                    request_deserializer=functions__pb2.ValidatorReq.FromString,
                    response_serializer=functions__pb2.ValidatorReply.SerializeToString,
            ),
            'nv_evaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.nv_evaluation,
                    request_deserializer=functions__pb2.NvEvaluationReq.FromString,
                    response_serializer=functions__pb2.NvEvaluationReply.SerializeToString,
            ),
            'question_to_query': grpc.unary_unary_rpc_method_handler(
                    servicer.question_to_query,
                    request_deserializer=functions__pb2.QuestionToQueryReq.FromString,
                    response_serializer=functions__pb2.QuestionToQueryReply.SerializeToString,
            ),
            'context_question_to_query': grpc.unary_unary_rpc_method_handler(
                    servicer.context_question_to_query,
                    request_deserializer=functions__pb2.ContextQuestionToQueryReq.FromString,
                    response_serializer=functions__pb2.ContextQuestionToQueryReply.SerializeToString,
            ),
            'context_question_to_answer': grpc.unary_unary_rpc_method_handler(
                    servicer.context_question_to_answer,
                    request_deserializer=functions__pb2.ContextQuestionToAnswerReq.FromString,
                    response_serializer=functions__pb2.ContextQuestionToAnswerReply.SerializeToString,
            ),
            'rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.rerank,
                    request_deserializer=functions__pb2.RerankReq.FromString,
                    response_serializer=functions__pb2.RerankReply.SerializeToString,
            ),
            'retrieval1': grpc.unary_unary_rpc_method_handler(
                    servicer.retrieval1,
                    request_deserializer=functions__pb2.Retrieval1Req.FromString,
                    response_serializer=functions__pb2.Retrieval1Reply.SerializeToString,
            ),
            'retrieval2': grpc.unary_unary_rpc_method_handler(
                    servicer.retrieval2,
                    request_deserializer=functions__pb2.Retrieval2Req.FromString,
                    response_serializer=functions__pb2.Retrieval2Reply.SerializeToString,
            ),
            'qa_evaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.qa_evaluation,
                    request_deserializer=functions__pb2.QaEvaluationReq.FromString,
                    response_serializer=functions__pb2.QaEvaluationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FunctionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FunctionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FunctionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def candidate_generation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/candidate_generation',
            functions__pb2.CandidateGenerationReq.SerializeToString,
            functions__pb2.CandidateGenerationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def column_filtering(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/column_filtering',
            functions__pb2.ColumnFilteringReq.SerializeToString,
            functions__pb2.ColumnFilteringReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def column_selection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/column_selection',
            functions__pb2.ColumnSelectionReq.SerializeToString,
            functions__pb2.ColumnSelectionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def context_retrieval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/context_retrieval',
            functions__pb2.ContextRetrievalReq.SerializeToString,
            functions__pb2.ContextRetrievalReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def entity_retrieval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/entity_retrieval',
            functions__pb2.EntityRetrievalReq.SerializeToString,
            functions__pb2.EntityRetrievalReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def evaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/evaluation',
            functions__pb2.EvaluationReq.SerializeToString,
            functions__pb2.EvaluationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def keyword_extraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/keyword_extraction',
            functions__pb2.KeywordExtractionReq.SerializeToString,
            functions__pb2.KeywordExtractionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def revision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/revision',
            functions__pb2.RevisionReq.SerializeToString,
            functions__pb2.RevisionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def table_selection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/table_selection',
            functions__pb2.TableSelectionReq.SerializeToString,
            functions__pb2.TableSelectionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def preprocess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/preprocess',
            functions__pb2.PreprocessReq.SerializeToString,
            functions__pb2.PreprocessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def processor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/processor',
            functions__pb2.ProcessorReq.SerializeToString,
            functions__pb2.ProcessorReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def composer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/composer',
            functions__pb2.ComposerReq.SerializeToString,
            functions__pb2.ComposerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def validator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/validator',
            functions__pb2.ValidatorReq.SerializeToString,
            functions__pb2.ValidatorReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def nv_evaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/nv_evaluation',
            functions__pb2.NvEvaluationReq.SerializeToString,
            functions__pb2.NvEvaluationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def question_to_query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/question_to_query',
            functions__pb2.QuestionToQueryReq.SerializeToString,
            functions__pb2.QuestionToQueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def context_question_to_query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/context_question_to_query',
            functions__pb2.ContextQuestionToQueryReq.SerializeToString,
            functions__pb2.ContextQuestionToQueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def context_question_to_answer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/context_question_to_answer',
            functions__pb2.ContextQuestionToAnswerReq.SerializeToString,
            functions__pb2.ContextQuestionToAnswerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/rerank',
            functions__pb2.RerankReq.SerializeToString,
            functions__pb2.RerankReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def retrieval1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/retrieval1',
            functions__pb2.Retrieval1Req.SerializeToString,
            functions__pb2.Retrieval1Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def retrieval2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/retrieval2',
            functions__pb2.Retrieval2Req.SerializeToString,
            functions__pb2.Retrieval2Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def qa_evaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/qa_evaluation',
            functions__pb2.QaEvaluationReq.SerializeToString,
            functions__pb2.QaEvaluationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
