# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: functions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'functions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66unctions.proto\"$\n\rPreprocessReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"5\n\x0fPreprocessReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"#\n\x0cProcessorReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"4\n\x0eProcessorReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\"\n\x0b\x43omposerReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"3\n\rComposerReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"$\n\rTranslatorReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"5\n\x0fTranslatorReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"#\n\x0cValidatorReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"4\n\x0eValidatorReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"&\n\x0fNvEvaluationReq\x12\x13\n\x0bparams_json\x18\x01 \x01(\t\"7\n\x11NvEvaluationReply\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xac\x02\n\x0f\x46unctionService\x12.\n\npreprocess\x12\x0e.PreprocessReq\x1a\x10.PreprocessReply\x12+\n\tprocessor\x12\r.ProcessorReq\x1a\x0f.ProcessorReply\x12(\n\x08\x63omposer\x12\x0c.ComposerReq\x1a\x0e.ComposerReply\x12.\n\ntranslator\x12\x0e.TranslatorReq\x1a\x10.TranslatorReply\x12+\n\tvalidator\x12\r.ValidatorReq\x1a\x0f.ValidatorReply\x12\x35\n\rnv_evaluation\x12\x10.NvEvaluationReq\x1a\x12.NvEvaluationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'functions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPROCESSREQ']._serialized_start=19
  _globals['_PREPROCESSREQ']._serialized_end=55
  _globals['_PREPROCESSREPLY']._serialized_start=57
  _globals['_PREPROCESSREPLY']._serialized_end=110
  _globals['_PROCESSORREQ']._serialized_start=112
  _globals['_PROCESSORREQ']._serialized_end=147
  _globals['_PROCESSORREPLY']._serialized_start=149
  _globals['_PROCESSORREPLY']._serialized_end=201
  _globals['_COMPOSERREQ']._serialized_start=203
  _globals['_COMPOSERREQ']._serialized_end=237
  _globals['_COMPOSERREPLY']._serialized_start=239
  _globals['_COMPOSERREPLY']._serialized_end=290
  _globals['_TRANSLATORREQ']._serialized_start=292
  _globals['_TRANSLATORREQ']._serialized_end=328
  _globals['_TRANSLATORREPLY']._serialized_start=330
  _globals['_TRANSLATORREPLY']._serialized_end=383
  _globals['_VALIDATORREQ']._serialized_start=385
  _globals['_VALIDATORREQ']._serialized_end=420
  _globals['_VALIDATORREPLY']._serialized_start=422
  _globals['_VALIDATORREPLY']._serialized_end=474
  _globals['_NVEVALUATIONREQ']._serialized_start=476
  _globals['_NVEVALUATIONREQ']._serialized_end=514
  _globals['_NVEVALUATIONREPLY']._serialized_start=516
  _globals['_NVEVALUATIONREPLY']._serialized_end=571
  _globals['_FUNCTIONSERVICE']._serialized_start=574
  _globals['_FUNCTIONSERVICE']._serialized_end=874
# @@protoc_insertion_point(module_scope)
