# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import functions_pb2 as functions__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in functions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FunctionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.preprocess = channel.unary_unary(
                '/FunctionService/preprocess',
                request_serializer=functions__pb2.PreprocessReq.SerializeToString,
                response_deserializer=functions__pb2.PreprocessReply.FromString,
                _registered_method=True)
        self.processor = channel.unary_unary(
                '/FunctionService/processor',
                request_serializer=functions__pb2.ProcessorReq.SerializeToString,
                response_deserializer=functions__pb2.ProcessorReply.FromString,
                _registered_method=True)
        self.composer = channel.unary_unary(
                '/FunctionService/composer',
                request_serializer=functions__pb2.ComposerReq.SerializeToString,
                response_deserializer=functions__pb2.ComposerReply.FromString,
                _registered_method=True)
        self.translator = channel.unary_unary(
                '/FunctionService/translator',
                request_serializer=functions__pb2.TranslatorReq.SerializeToString,
                response_deserializer=functions__pb2.TranslatorReply.FromString,
                _registered_method=True)
        self.validator = channel.unary_unary(
                '/FunctionService/validator',
                request_serializer=functions__pb2.ValidatorReq.SerializeToString,
                response_deserializer=functions__pb2.ValidatorReply.FromString,
                _registered_method=True)
        self.nv_evaluation = channel.unary_unary(
                '/FunctionService/nv_evaluation',
                request_serializer=functions__pb2.NvEvaluationReq.SerializeToString,
                response_deserializer=functions__pb2.NvEvaluationReply.FromString,
                _registered_method=True)


class FunctionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def preprocess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def composer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def translator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def validator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nv_evaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FunctionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'preprocess': grpc.unary_unary_rpc_method_handler(
                    servicer.preprocess,
                    request_deserializer=functions__pb2.PreprocessReq.FromString,
                    response_serializer=functions__pb2.PreprocessReply.SerializeToString,
            ),
            'processor': grpc.unary_unary_rpc_method_handler(
                    servicer.processor,
                    request_deserializer=functions__pb2.ProcessorReq.FromString,
                    response_serializer=functions__pb2.ProcessorReply.SerializeToString,
            ),
            'composer': grpc.unary_unary_rpc_method_handler(
                    servicer.composer,
                    request_deserializer=functions__pb2.ComposerReq.FromString,
                    response_serializer=functions__pb2.ComposerReply.SerializeToString,
            ),
            'translator': grpc.unary_unary_rpc_method_handler(
                    servicer.translator,
                    request_deserializer=functions__pb2.TranslatorReq.FromString,
                    response_serializer=functions__pb2.TranslatorReply.SerializeToString,
            ),
            'validator': grpc.unary_unary_rpc_method_handler(
                    servicer.validator,
                    request_deserializer=functions__pb2.ValidatorReq.FromString,
                    response_serializer=functions__pb2.ValidatorReply.SerializeToString,
            ),
            'nv_evaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.nv_evaluation,
                    request_deserializer=functions__pb2.NvEvaluationReq.FromString,
                    response_serializer=functions__pb2.NvEvaluationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FunctionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FunctionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FunctionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def preprocess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/preprocess',
            functions__pb2.PreprocessReq.SerializeToString,
            functions__pb2.PreprocessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def processor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/processor',
            functions__pb2.ProcessorReq.SerializeToString,
            functions__pb2.ProcessorReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def composer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/composer',
            functions__pb2.ComposerReq.SerializeToString,
            functions__pb2.ComposerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def translator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/translator',
            functions__pb2.TranslatorReq.SerializeToString,
            functions__pb2.TranslatorReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def validator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/validator',
            functions__pb2.ValidatorReq.SerializeToString,
            functions__pb2.ValidatorReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def nv_evaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FunctionService/nv_evaluation',
            functions__pb2.NvEvaluationReq.SerializeToString,
            functions__pb2.NvEvaluationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
